spring:
  application:
    name: Say-instance

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

  instance:
    leaseRenewalIntervalInSeconds: 10

server:
  port: 8080
